function [ColCell,Col]=gaia_dr1_cat_columns
% Get the GAIA-DR1 secondary catalog column names
% Description: Get the GAIA-DR1 secondary catalog column names
% Input  : null
% Output : - Cell array of column names.
%          - Structure of column names.
% Example: [ColCell,Col]=VO.prep.GAIA.gaia_dr1_cat_columns
% Reliable: 2

ColCell = {'solution_id','source_id','random_index','ref_epoch',...
           'ra','ra_error','dec','dec_error','parallax','parallax_error',...
           'pmra','pmra_error','pmdec','pmdec_error',...
           'ra_dec_corr','ra_parallax_corr','ra_pmra_corr','ra_pmdec_corr',...
           'dec_parallax_corr','dec_pmra_corr','dec_pmdec_corr','parallax_pmra_corr','parallax_pmdec_corr','pmra_pmdec_corr',...
           'astrometric_n_obs_al','astrometric_n_obs_ac','astrometric_n_good_obs_al','astrometric_n_good_obs_ac',...
           'astrometric_n_bad_obs_al','astrometric_n_bad_obs_ac','astrometric_delta_q',...
           'astrometric_excess_noise','astrometric_excess_noise_sig','astrometric_primary_flag',...
           'astrometric_relegation_factor','astrometric_weight_al','astrometric_weight_ac',...
           'astrometric_priors_used','matched_observations','duplicated_source',...
           'scan_direction_strength_k1','scan_direction_strength_k2',...
           'scan_direction_strength_k3','scan_direction_strength_k4',...
           'scan_direction_mean_k1','scan_direction_mean_k2',...
           'scan_direction_mean_k3','scan_direction_mean_k4',...
           'phot_g_n_obs','phot_g_mean_flux','phot_g_mean_flux_error',...
           'phot_g_mean_mag','phot_variable_flag',...
           'l','b','ecl_lon','ecl_lat'};
       
       
N   = numel(ColCell);
Col = cell2struct(num2cell(1:1:N),ColCell,2);
